name: Build for Linux

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
     - uses: microsoft/setup-msbuild@v1.1
       with:
         channel: 'stable'
         architecture: x64
     - name: Create .env file
       run: | 
         echo "${{ secrets.ENV_FILE }}" > .env
     - name: Install Linux Build Tools
       run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev 
     - name: Setup Flutter SDK & Build
       run: |
         flutter config --enable-linux-desktop
         flutter pub get
         flutter build linux
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
        name: agito-linux
        path: build/linux/x64/release/bundle